 DROP TABLE used_cars;
 DROP TABLE prices;
 DROP TABLE fuel_efficiency;
 DROP TABLE analysis_ready_table;
 
 CREATE TABLE used_cars (
							ID SERIAL PRIMARY KEY,
	 						YEAR integer NOT NULL,
							MAKE VARCHAR(200) NOT NULL,
							MODEL VARCHAR(200),
							TRIM VARCHAR(200) NULL,
	 					    MILES integer,
							BODY_TYPE VARCHAR(200) NULL,
							VEHICLE_TYPE VARCHAR(200) NULL,
					        TRANSMISSION VARCHAR(200) NULL,
							DRIVETRAIN VARCHAR(200) NULL,
							FUEL_TYPE VARCHAR(200) NULL,
							ENGINE_SIZE VARCHAR(200) NULL
						);	
						
CREATE TABLE prices (
	                  ID SERIAL PRIMARY KEY,
 					  YEAR integer NOT NULL,
					  MAKE VARCHAR(200) NOT NULL,
					  MODEL VARCHAR(200),
					  PRICE DECIMAL
					);
					
CREATE TABLE fuel_efficiency (
							    ID SERIAL PRIMARY KEY,
								YEAR integer NOT NULL,
								MAKE VARCHAR(200) NOT NULL,
								MODEL VARCHAR(200),
								HYBRID_NONHYBRID VARCHAR(200) NOT NULL,
								STANDARD_TYPE VARCHAR(200) NOT NULL,
								EPA_RATING_CITY integer,
								TOTAL_ACTUAL_MILES integer,
								TOTAL_ACTUAL_FUEL integer,
								EPA_EXPECTED_FUEL DECIMAL,
								ACTUAL_FUEL_ECONOMY_GEOTAB DECIMAL,
								DIFFERENCE_ACTUAL_TO_EPA DECIMAL,
								ESTIMATED_FUEL_COSTS_PER_GALLON DECIMAL,
								FUEL_COSTS_PER_MILE DECIMAL
							);
							
CREATE TABLE analysis_ready_table ();